"""initial schema

Revision ID: 9b59a236190d
Revises:
Create Date: 2026-08-10 09:24:09.710318

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b59a236190d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index("ix_messages_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_messages_request_id", ["request_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_user_id", ["user_id"], unique=False)

    op.create_table(
        "execution_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("execution_log", schema=None) as batch_op:
        batch_op.create_index("ix_execution_log_request_id", ["request_id"], unique=False)

    op.execute(
        """
        CREATE TRIGGER execution_log_no_update
        BEFORE UPDATE ON execution_log
        BEGIN
            SELECT RAISE(ABORT, 'execution_log is append-only');
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER execution_log_no_delete
        BEFORE DELETE ON execution_log
        BEGIN
            SELECT RAISE(ABORT, 'execution_log is append-only');
        END
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS execution_log_no_delete")
    op.execute("DROP TRIGGER IF EXISTS execution_log_no_update")
    with op.batch_alter_table("execution_log", schema=None) as batch_op:
        batch_op.drop_index("ix_execution_log_request_id")

    op.drop_table("execution_log")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_user_id")

    op.drop_table("tasks")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_request_id")
        batch_op.drop_index("ix_messages_created_at")

    op.drop_table("messages")
    # ### end Alembic commands ###
