"""role binding

Revision ID: 263f2a7d3b88
Revises: 
Create Date: 2026-08-15 09:00:46.217706

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '263f2a7d3b88'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_binding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('engine_id', sa.String(length=36), nullable=True),
    sa.Column('locality', sa.String(length=8), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'role', name='uq_role_binding_project_role')
    )
    with op.batch_alter_table('role_binding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_binding_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_binding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_binding_project_id'))

    op.drop_table('role_binding')
    # ### end Alembic commands ###
