"""step transitions

Revision ID: 2526c2dce48e
Revises: e2e0dfa6641a
Create Date: 2026-08-17 19:20:03.942988

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2526c2dce48e'
down_revision: str | None = 'e2e0dfa6641a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_transition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=False),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['action_step.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_transition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_transition_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_transition_step_id'), ['step_id'], unique=False)
        batch_op.create_index('ix_step_transition_step_occurred', ['step_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_transition_task_id'), ['task_id'], unique=False)

    op.execute(
        "CREATE TRIGGER step_transition_no_update "
        "BEFORE UPDATE ON step_transition "
        "BEGIN SELECT RAISE(ABORT, 'step_transition is append-only'); END"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS step_transition_no_update")

    with op.batch_alter_table('step_transition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_transition_task_id'))
        batch_op.drop_index('ix_step_transition_step_occurred')
        batch_op.drop_index(batch_op.f('ix_step_transition_step_id'))
        batch_op.drop_index(batch_op.f('ix_step_transition_plan_id'))

    op.drop_table('step_transition')
    # ### end Alembic commands ###
