"""upload scan truncation

Revision ID: 3e1896f7cc91
Revises: f0516ff680a8
Create Date: 2026-08-16 07:46:39.655608

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3e1896f7cc91'
down_revision: str | None = 'f0516ff680a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_directories', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.add_column(sa.Column('truncated', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_scan', schema=None) as batch_op:
        batch_op.drop_column('truncated')
        batch_op.drop_column('skipped_directories')

    # ### end Alembic commands ###
