"""action plan persistence

Revision ID: 442f31ff144e
Revises: 64941d093c49
Create Date: 2026-08-17 06:54:27.522077

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '442f31ff144e'
down_revision: str | None = '64941d093c49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('scope_root', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('target_engine_id', sa.String(length=36), nullable=True),
    sa.Column('target_model_id', sa.String(length=200), nullable=True),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('gated_count', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('repaired', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('prompt_name', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_plan_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plan_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_action_plan_task_created', ['task_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_plan_task_id'), ['task_id'], unique=False)

    op.create_table('action_step',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('service', sa.String(length=24), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('confirmation_reason', sa.Text(), nullable=True),
    sa.Column('on_failure', sa.String(length=12), nullable=False),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('criterion_refs', sa.JSON(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'position', name='uq_step_plan_position')
    )
    with op.batch_alter_table('action_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_step_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_step_plan_id'))

    op.drop_table('action_step')
    with op.batch_alter_table('action_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_plan_task_id'))
        batch_op.drop_index('ix_action_plan_task_created')
        batch_op.drop_index(batch_op.f('ix_action_plan_request_id'))
        batch_op.drop_index(batch_op.f('ix_action_plan_project_id'))

    op.drop_table('action_plan')
    # ### end Alembic commands ###
