"""analyst brief and clarification

Revision ID: 64941d093c49
Revises: f8f92f36fc9d
Create Date: 2026-08-16 12:09:23.248956

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '64941d093c49'
down_revision: str | None = 'f8f92f36fc9d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_brief',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('conceive_revision_number', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('interpreted_goal', sa.Text(), nullable=False),
    sa.Column('project_type', sa.String(length=16), nullable=False),
    sa.Column('known_constraints', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('out_of_scope', sa.JSON(), nullable=False),
    sa.Column('seeded_success_criteria', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('unresolved_fields', sa.JSON(), nullable=False),
    sa.Column('contradictions', sa.JSON(), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'round', name='uq_brief_project_round')
    )
    with op.batch_alter_table('project_brief', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_brief_project_id'), ['project_id'], unique=False)

    op.create_table('clarification_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['project_brief.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clarification_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarification_request_brief_id'), ['brief_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clarification_request_project_id'), ['project_id'], unique=False)

    op.create_table('clarification_question',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=False),
    sa.Column('why_asked', sa.Text(), nullable=False),
    sa.Column('answer_kind', sa.String(length=16), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['clarification_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clarification_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarification_question_request_id'), ['request_id'], unique=False)

    op.create_table('clarification_answer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('choice', sa.String(length=200), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['clarification_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', name='uq_answer_question')
    )
    with op.batch_alter_table('clarification_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarification_answer_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clarification_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarification_answer_question_id'))

    op.drop_table('clarification_answer')
    with op.batch_alter_table('clarification_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarification_question_request_id'))

    op.drop_table('clarification_question')
    with op.batch_alter_table('clarification_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarification_request_project_id'))
        batch_op.drop_index(batch_op.f('ix_clarification_request_brief_id'))

    op.drop_table('clarification_request')
    with op.batch_alter_table('project_brief', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_brief_project_id'))

    op.drop_table('project_brief')
    # ### end Alembic commands ###
