"""reconciliation records

Revision ID: e2e0dfa6641a
Revises: 442f31ff144e
Create Date: 2026-08-17 09:48:35.372291

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e2e0dfa6641a'
down_revision: str | None = '442f31ff144e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('halt_reason', sa.String(length=16), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=False),
    sa.Column('steps_completed', sa.Integer(), nullable=False),
    sa.Column('steps_never_attempted', sa.Integer(), nullable=False),
    sa.Column('criteria_verified_ids', sa.JSON(), nullable=False),
    sa.Column('criteria_unverified_ids', sa.JSON(), nullable=False),
    sa.Column('touched_paths', sa.JSON(), nullable=False),
    sa.Column('percentage_at_halt', sa.Float(), nullable=False),
    sa.Column('plain_summary', sa.String(length=1000), nullable=False),
    sa.Column('written_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['action_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_record_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_record_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_record_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_record_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_reconciliation_task_written', ['task_id', 'written_at'], unique=False)

    op.create_table('step_outcome',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('touched_paths', sa.JSON(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['reconciliation_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['action_step.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'position', name='uq_outcome_record_position')
    )
    with op.batch_alter_table('step_outcome', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_outcome_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_outcome_step_id'), ['step_id'], unique=False)

    op.execute(
        "CREATE TRIGGER reconciliation_record_no_update "
        "BEFORE UPDATE ON reconciliation_record "
        "BEGIN SELECT RAISE(ABORT, 'reconciliation_record is append-only'); END"
    )
    op.execute(
        "CREATE TRIGGER step_outcome_no_update "
        "BEFORE UPDATE ON step_outcome "
        "BEGIN SELECT RAISE(ABORT, 'step_outcome is append-only'); END"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS step_outcome_no_update")
    op.execute("DROP TRIGGER IF EXISTS reconciliation_record_no_update")

    with op.batch_alter_table('step_outcome', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_outcome_step_id'))
        batch_op.drop_index(batch_op.f('ix_step_outcome_record_id'))

    op.drop_table('step_outcome')
    with op.batch_alter_table('reconciliation_record', schema=None) as batch_op:
        batch_op.drop_index('ix_reconciliation_task_written')
        batch_op.drop_index(batch_op.f('ix_reconciliation_record_task_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_record_request_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_record_project_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_record_plan_id'))

    op.drop_table('reconciliation_record')
    # ### end Alembic commands ###
