"""project spine

Revision ID: e6532fd9ba49
Revises: 
Create Date: 2026-08-15 16:07:25.800273

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e6532fd9ba49'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('goal', sa.String(length=500), nullable=False),
    sa.Column('project_type', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_environment', sa.String(length=200), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('do_not_touch', sa.JSON(), nullable=False),
    sa.Column('sensitivity_flags', sa.JSON(), nullable=False),
    sa.Column('success_criteria', sa.JSON(), nullable=False),
    sa.Column('referenced_project_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index('uq_project_single_active', ['state'], unique=True, sqlite_where=sa.text("state = 'active'"))

    op.create_table('project_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('criterion_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('to_state', sa.String(length=24), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_event_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index('ix_project_event_project_occurred', ['project_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_event_task_id'), ['task_id'], unique=False)

    op.create_table('conceive',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('current_revision_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('project_material',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_material_project_id'), ['project_id'], unique=False)

    op.create_table('task_node',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('assigned_role', sa.String(length=16), nullable=False),
    sa.Column('action_plan_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['task_node.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_node_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_node_project_id'), ['project_id'], unique=False)

    op.create_table('acceptance_criterion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('statement', sa.String(length=500), nullable=False),
    sa.Column('check_kind', sa.String(length=16), nullable=False),
    sa.Column('check_spec', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task_node.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acceptance_criterion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acceptance_criterion_task_id'), ['task_id'], unique=False)

    op.create_table('conceive_revision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conceive_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conceive_id'], ['conceive.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conceive_id', 'revision_number', name='uq_conceive_revision_conceive_number')
    )
    with op.batch_alter_table('conceive_revision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conceive_revision_conceive_id'), ['conceive_id'], unique=False)

    op.create_table('upload_scan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_tree', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('dependency_manifests', sa.JSON(), nullable=False),
    sa.Column('entry_points', sa.JSON(), nullable=False),
    sa.Column('secret_findings', sa.JSON(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['project_material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id')
    )
    with op.batch_alter_table('upload_scan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_scan_project_id'), ['project_id'], unique=False)

    op.create_table('evidence_ref',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ref', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['acceptance_criterion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_ref', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_ref_criterion_id'), ['criterion_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_ref', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_ref_criterion_id'))

    op.drop_table('evidence_ref')
    with op.batch_alter_table('upload_scan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_scan_project_id'))

    op.drop_table('upload_scan')
    with op.batch_alter_table('conceive_revision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conceive_revision_conceive_id'))

    op.drop_table('conceive_revision')
    with op.batch_alter_table('acceptance_criterion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acceptance_criterion_task_id'))

    op.drop_table('acceptance_criterion')
    with op.batch_alter_table('task_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_node_project_id'))
        batch_op.drop_index(batch_op.f('ix_task_node_parent_id'))

    op.drop_table('task_node')
    with op.batch_alter_table('project_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_material_project_id'))

    op.drop_table('project_material')
    op.drop_table('conceive')
    with op.batch_alter_table('project_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_event_task_id'))
        batch_op.drop_index('ix_project_event_project_occurred')
        batch_op.drop_index(batch_op.f('ix_project_event_criterion_id'))

    op.drop_table('project_event')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index('uq_project_single_active', sqlite_where=sa.text("state = 'active'"))

    op.drop_table('project')
    # ### end Alembic commands ###
