"""event material reference

Revision ID: f8f92f36fc9d
Revises: 3e1896f7cc91
Create Date: 2026-08-16 08:26:30.889932

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f8f92f36fc9d'
down_revision: str | None = '3e1896f7cc91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_event_material_id'), ['material_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_event_material_id'))
        batch_op.drop_column('material_id')

    # ### end Alembic commands ###
